target 'iOSQuestions' do
  use_frameworks!
  
  pod 'IQKeyboardManagerSwift', '~> 6.5.6'
  pod 'SnapKit', '~> 4.2.0'
  pod 'HandyJSON', :git => 'https://github.com/alibaba/HandyJSON.git', :branch => 'dev_for_swift5.0' # (5.0.0-beta.1)
  #工具库
  pod 'MJFramework', '~> 1.2.2'
  
end
